# Generated by Django 3.0.3 on 2020-03-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('adresse', models.CharField(max_length=200)),
                ('codePostal', models.BigIntegerField()),
                ('ville', models.CharField(default='Mulhouse', max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('website', models.URLField()),
                ('available', models.BooleanField(default=True)),
                ('picture', models.URLField()),
            ],
        ),
    ]
