# Generated by Django 3.0.3 on 2020-03-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('adresse', models.CharField(max_length=200)),
                ('codePostal', models.BigIntegerField(default=68100)),
                ('ville', models.CharField(default='Mulhouse', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='téléphone')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('available', models.BooleanField(default=True, verbose_name='disponnible')),
                ('image', models.URLField(blank=True, verbose_name='image')),
            ],
        ),
    ]
